n = 'python_programming_01'
"""
print(n)
print(n[0])
print(n[1])
print(n[0:5])
print(n[5:])
print(n[::])
print(n[::2])
print(n[0:15:3])
print(n[-1])
print(n[-4:-2])
print(n[::-1])
"""
print(n.capitalize())
print(n.upper())
print(n.lower())
print(n.split("_"))
print(n.center(30,'|'))
print(n.count("p"))
print(n.find("m"))
print(n.isalnum())
print(n.replace("python","linux"))
a = 1
print(n.replace("python","unix"),":", a)